name: "Test"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect /dev/kvm
        run: |
          id
          stat /dev/kvm
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Build
        run: |
          id
          stat /dev/kvm          
          nix run nixpkgs#nix-info -- --markdown
          nix flake metadata nixpkgs
          nix build --no-link --print-build-logs --print-out-paths nixpkgs#pkgsStatic.hello

      - name: docker
        run: |
          # podman images || true
          docker images || true
          docker run alpine:3.18 sh -c 'cat /etc/os-release'

      - name: nix build ...
        run: |
          # echo 2_3
          # nix \
          # build \
          # --no-link \
          # --print-build-logs \
          # --print-out-paths \
          # github:NixOS/nixpkgs/90055d5e616bd943795d38808c94dbf0dd35abe8#pkgsStatic.nixVersions.nix_2_3
          # echo 2_18
          # sha512sum $(
          #   nix \
          #   build \
          #   --rebuild \
          #   --no-link \
          #   --print-build-logs \
          #   --print-out-paths \
          #   github:NixOS/nixpkgs/90055d5e616bd943795d38808c94dbf0dd35abe8#pkgsStatic.nixVersions.nix_2_18
          # )/bin/nix
          #
          # nix build --print-build-logs --print-out-paths github:NixOS/nix/20f04721492396570524509a9de45bc1e3a1524c#nix-static
          # nix build --rebuild --print-build-logs --print-out-paths github:NixOS/nix/20f04721492396570524509a9de45bc1e3a1524c#nix-static
          #
          # sha512sum $(
          #   nix \
          #   build \
          #   --rebuild \
          #   --no-link \
          #   --print-build-logs \
          #   --print-out-paths \
          #   github:NixOS/nix/93e8660bba42c8c90fcc1455ebb6e8631b66d4cb#hydraJobs.buildStatic.x86_64-linux
          # )/bin/nix
          # ./minimal.sh
          # ls -lah /nix/store/z8s3ajlqb0hbabzr7j4cnji1fr4iz8a4-nixos-23.11.6510.a5e4bbc
          curl https://hydra.nixos.org/build/230309007/reproduce | bash 
          sha256sum /nix/store/695s2nlp1jh67d9qdm0xcv7m3m9r1821-nixos-minimal-22.11.4773.ea4c80b39be4-x86_64-linux.iso/iso/nixos-minimal-22.11.4773.ea4c80b39be4-x86_64-linux.iso

#      - name: nix build ...
#        run: |
#          nix build --no-link --print-build-logs \
#          --file nixos-test-python-cross.nix

#      - name: nix build nixosTest
#        run: |
#          nix build --no-link --print-build-logs github:ES-Nix/nixosTest/2f37db3fe507e725f5e94b42a942cdfef30e5d75#checks.x86_64-linux.test-nixos
