name: "Test"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect /dev/kvm
        run: |
          id
          stat /dev/kvm
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Build
        run: |
          nix run nixpkgs#nix-info -- --markdown
          nix flake metadata nixpkgs
          nix build --no-link --print-build-logs --print-out-paths nixpkgs#pkgsStatic.hello
      - name: Inspect /dev/kvm
        run: |
          id
          stat /dev/kvm

      - name: nix build ... pkgsStatic
        run: |
          nix build --no-link --print-build-logs \
          --file nixos-test-python-corss.nix

#      - name: nix build nixosTest
#        run: |
#          nix build --no-link --print-build-logs github:ES-Nix/nixosTest/2f37db3fe507e725f5e94b42a942cdfef30e5d75#checks.x86_64-linux.test-nixos
