name: "Test"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect /dev/kvm
        run: |
          id
          stat /dev/kvm
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Build
        run: |
          id
          stat /dev/kvm          
          nix run nixpkgs#nix-info -- --markdown
          nix flake metadata nixpkgs
          nix build --no-link --print-build-logs --print-out-paths nixpkgs#pkgsStatic.hello

      - name: docker
        run: |
          # podman images || true
          docker images || true
          docker run alpine:3.18 sh -c 'cat /etc/os-release'

      - name: nix build ...
        run: |
          nix \
          build \
          --no-link \
          --print-build-logs \
          --print-out-paths \
          github:NixOS/nixpkgs/90055d5e616bd943795d38808c94dbf0dd35abe8#pkgsStatic.nixVersions.nix_2_3
          # nix build --print-build-logs --print-out-paths github:NixOS/nix/20f04721492396570524509a9de45bc1e3a1524c#nix-static
          # nix build --rebuild --print-build-logs --print-out-paths github:NixOS/nix/20f04721492396570524509a9de45bc1e3a1524c#nix-static

#      - name: nix build ...
#        run: |
#          nix build --no-link --print-build-logs \
#          --file nixos-test-python-cross.nix

#      - name: nix build nixosTest
#        run: |
#          nix build --no-link --print-build-logs github:ES-Nix/nixosTest/2f37db3fe507e725f5e94b42a942cdfef30e5d75#checks.x86_64-linux.test-nixos
