name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v16
      with:
        # install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        # install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes ca-derivations
          sandbox = false
    - run: |
        nix flake --version
        nix flake info nixpkgs
    - run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --no-install-suggests -y uidmap
    - run: nix profile install github:ES-Nix/podman-rootless/from-nixpkgs
    - run: podman --version && podman info
    - run: ./run.sh
    #- run: nix profile install nixpkgs#podman
    #- run: nix build github:ES-Nix/podman-rootless/from-nixpkgs
    #- run: nix build nixpkgs#podman
    #- run: ./result/bin/podman --version && ./result/bin/podman info
    #- run: nix build nixpkgs#python3Minimal && echo $(result/bin/python) && result/bin/python --version
    #- run: nix build github:cole-h/nixos-config/6779f0c3ee6147e5dcadfbaff13ad57b1fb00dc7#iso
    #- run: nix build github:NixOS/nix#nix-static
    #- run: nix develop github:ES-Nix/poetry2nix-examples/2cb6663e145bbf8bf270f2f45c869d69c657fef2
    #- run: nix build github:ES-Nix/nix-qemu-kvm/65d1358567e6c8309158dc04d299090846576fe2#qemu.prepare
